demoproject/inmakes_product_folder/moviesproject/moviesapp/urls.py
from django.urls import path
from . import views

app_name='moviesapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movies_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

demoproject/inmakes_product_folder/moviesproject/moviesproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("moviesapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demoproject/inmakes_product_folder/moviesproject/moviesapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__ (self):
        return self.name

demoproject/inmakes_product_folder/moviesproject/moviesapp/forms.py
from django import forms
from.models import Movies

class MovieForm (forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

demoproject/inmakes_product_folder/moviesproject/moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Movies
from . forms import MovieForm
# Create your views here.
def index(request):
    movies=Movies.objects.all()
    context = {
        'movies_list':movies
    }
    return render(request,'index.html',context)

def detail(request,movies_id):
    movies=Movies.objects.get(id=movies_id)
    return render(request,"detail.html",{'movie':movies})

def add_movie(request):
    if request.method=="POSTT":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movies=Movies(name=name, desc=desc, year=year, img=img)
        movies.save()
        return render(request,'add.html')

def update(request,id):
    movies=Movies.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES, instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movies':movies})

def delete(request,id):
    if request.method=='POST':
        movies=Movies.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

demoproject/inmakes_product_folder/moviesproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<from method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter your movie name"><br>

        <input type="text" name="desc" placeholder="Enter your movie description"><br>

        <input type="text" name="year" placeholder="Enter your movie year"><br>

        <input type="file" name="img"><br>

        <input type="submit">

</from>

{% endblock %}

demoproject/inmakes_product_folder/moviesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet"href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      online Movie store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

demoproject/inmakes_product_folder/moviesproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>

demoproject/inmakes_product_folder/moviesproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movie.img.url}}" width="250" height="250">
        </div>
<div class="col-md-6">
    {{movie.name}}
    {{movie.desc}}
    {{movie.year}}
    <a class= "btn btn-warning" href="{% url 'moviesapp:update' movie.id %}">update</a>
    <a class= "btn btn-danger" href="{% url 'moviesapp:delete' movie.id %}">Delete</a>
</div>

    </div>

</div>
{% endblock %}

demoproject/inmakes_product_folder/moviesproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

demoproject/inmakes_product_folder/moviesproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movies_list %}
        <div class="col-md-3">
            <div class="card">
  <img src="{{i.img.url}}" class="card-img-top" alt=" " height="200">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'moviesapp:detail' i.id %}" class="btn btn-primary">view details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}